site_name: 'Kotlin ECS'
site_url: 'https://juan-medina.github.io/kecs/'
site_description: 'tbc.'
site_author: 'Juan Medina'
copyright: '© 2020 Juan Medina'

repo_url: https://github.com/juan-medina/kecs
repo_name: 'GitHub'
edit_uri: '/juan-medina/kecs/blob/main/api/docs'
pages:
    - Home: 'index.md'
    - What is a ECS: 'ecs.md'
    - User Guide: 'guide.md'
    - Advance Example : 'example.md'
    - API Documentation: 'packages/-k-e-c-s/index.md'
theme:
    name: material
    logo: 'icon.svg'
    favicon: 'icon.svg'
    palette:
        scheme: slate
extra_css:
    - stylesheets/codehilite.css
docs_dir: api/docs
site_dir: docs/
markdown_extensions:
    - codehilite
    - smarty
    - codehilite:
          guess_lang: false
    - footnotes
    - meta
    - toc:
          permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.snippets:
          check_paths: true
    - tables
    - admonition
    - attr_list
